<a href="https://colab.research.google.com/github/KARTIKEYgarg1/udemy-data-science-and-ml/blob/master/Lecture108_KNN_CLASSIFIER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.datasets import load_iris
import numpy as np
data=load_iris()
X=data.data
Y=data.target
np.unique(Y)

array([0, 1, 2])

In [18]:
def mySplit(X,Y,testSize):
  idx=np.random.permutation(np.arange(len(Y)))
  tS=int(np.floor(testSize*len(Y)))
  tempX=idx[tS:]
  tempY=idx[:tS]
  trainX=X[tempX,:]
  trainY=Y[tempX]
  testX=X[tempY,:]
  testY=Y[tempY]
  return trainX,trainY,testX,testY
trainX,trainY,testX,testY=mySplit(X,Y,0.2)

In [21]:
testX.shape

(30, 4)

In [26]:
D=np.sum(trainX[:,np.newaxis,:]-testX[np.newaxis,:,:]**2,axis=2)
D

array([[-86.42, -34.99, -25.27, ..., -67.39, -77.93, -26.76],
       [-90.62, -39.19, -29.47, ..., -71.59, -82.13, -30.96],
       [-88.22, -36.79, -27.07, ..., -69.19, -79.73, -28.56],
       ...,
       [-87.92, -36.49, -26.77, ..., -68.89, -79.43, -28.26],
       [-92.42, -40.99, -31.27, ..., -73.39, -83.93, -32.76],
       [-86.02, -34.59, -24.87, ..., -66.99, -77.53, -26.36]])

In [27]:
ndix=np.argsort(D,axis=1)
ndix

array([[23,  5, 17, ..., 21, 16, 15],
       [23,  5, 17, ..., 21, 16, 15],
       [23,  5, 17, ..., 21, 16, 15],
       ...,
       [23,  5, 17, ..., 21, 16, 15],
       [23,  5, 17, ..., 21, 16, 15],
       [23,  5, 17, ..., 21, 16, 15]])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
