<a href="https://colab.research.google.com/github/KARTIKEYgarg1/udemy-data-science-and-ml/blob/master/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range(5):
  print(i)
else:
  print("done")

0
1
2
3
4
done


In [ ]:
D={'apple':50,'mango':90}
for x in D:
  print(x,D[x])

apple 50
mango 90


In [ ]:
len??

In [ ]:
len?

In [ ]:
def samp():
  print("wow")
print(samp())

wow
None


In [ ]:
def sampl(x=0):
  print(x)
sampl(5)
sampl()

5
0


In [ ]:
"""5^1 % 2"""
pow(5,1,2)

1

In [ ]:
x="You are the best"
print(x[::3])
print(x[::-1])
print(x[::1])

Y ehbt
tseb eht era uoY
You are the best


In [ ]:
L=[1,2,3,4]
L2=L
print(L)
print(L2)
L2[3]="four"
print(L)
print(L2)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 'four']
[1, 2, 3, 'four']


In [ ]:
import numpy as np
a=np.array((1,2,3,4,5))
b=np.array((1,2,3,4,5),dtype="f")
c=np.array([ [ [-1,-2],[1,2],[3,4] ],[ [5,6],[7,8],[9,10] ]])
print(a.dtype)
print(a.dtype)
print(b.dtype)
print(c.ndim)
print(c[0][1])
print(c[1,0])
print(c)
print(c.shape)
c=c.reshape(2,2,3)
print(c)
print(c.shape)

int64
int64
float32
3
[1 2]
[5 6]
[[[-1 -2]
  [ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]]
(2, 3, 2)
[[[-1 -2  1]
  [ 2  3  4]]

 [[ 5  6  7]
  [ 8  9 10]]]
(2, 2, 3)


In [2]:
import numpy as np
x=np.array([0,2,1],ndmin=4)
A=np.arange(30,100,3)
B=np.random.permutation(np.arange(10))
print(x)
print(x.shape)
print(A)
print(B)
print(np.random.randint(20,30))
print(np.random.rand(10))

[[[[0 2 1]]]]
(1, 1, 1, 3)
[30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99]
[7 8 0 9 5 4 2 6 3 1]
23
[0.99932905 0.44585054 0.29450324 0.16172393 0.06718186 0.66751722
 0.5750769  0.53839529 0.30901079 0.96206506]


In [9]:
b=np.round(10*np.random.rand(10))
%timeit sum(b)
%timeit np.sum(b)

1.89 µs ± 7.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.93 µs ± 79.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
import pandas as pd
data=pd.Series([25,36,41,5],index=['a','b','c','s'])
data1=pd.Series([2,6,1,51])
data2=pd.Series([1,2,7,8],index=['a','b','c','d'])
# data
# data.values
# data.index
# data1
# data['a':'c']
D=pd.DataFrame({'Marks':data,'Grades':data2})
# D
D.T

a     b     c    d    s
Marks   25.0  36.0  41.0  NaN  5.0
Grades   1.0   2.0   7.0  8.0  NaN

In [27]:
D['Scaled']=100*(D['Marks']/90)
print(D)

   Marks  Grades     Scaled
a   25.0     1.0  27.777778
b   36.0     2.0  40.000000
c   41.0     7.0  45.555556
d    NaN     8.0        NaN
s    5.0     NaN   5.555556


In [28]:
del D['Grades']
D

Marks     Scaled
a   25.0  27.777778
b   36.0  40.000000
c   41.0  45.555556
d    NaN        NaN
s    5.0   5.555556

In [30]:
G=D[D['Marks']>10]
G

Marks     Scaled
a   25.0  27.777778
b   36.0  40.000000
c   41.0  45.555556

In [33]:
D.fillna(0)

Marks     Scaled
a   25.0  27.777778
b   36.0  40.000000
c   41.0  45.555556
d    0.0   0.000000
s    5.0   5.555556

In [35]:
x=pd.read_csv("covid19.csv")
x.head()

Unnamed: 0  SNo ObservationDate Province/State  Country/Region  \
0           0    1       1/22/2020          Anhui  Mainland China   
1           1    2       1/22/2020        Beijing  Mainland China   
2           2    3       1/22/2020      Chongqing  Mainland China   
3           3    4       1/22/2020         Fujian  Mainland China   
4           4    5       1/22/2020          Gansu  Mainland China   

       Last Update  Confirmed  Deaths  Recovered  
0  1/22/2020 17:00          1       0          0  
1  1/22/2020 17:00         14       0          0  
2  1/22/2020 17:00          6       0          0  
3  1/22/2020 17:00          1       0          0  
4  1/22/2020 17:00          0       0          0