<a href="https://colab.research.google.com/github/KARTIKEYgarg1/udemy-data-science-and-ml/blob/master/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range(5):
  print(i)
else:
  print("done")

0
1
2
3
4
done


In [ ]:
D={'apple':50,'mango':90}
for x in D:
  print(x,D[x])

apple 50
mango 90


In [ ]:
len??

In [ ]:
len?

In [ ]:
def samp():
  print("wow")
print(samp())

wow
None


In [ ]:
def sampl(x=0):
  print(x)
sampl(5)
sampl()

5
0


In [ ]:
"""5^1 % 2"""
pow(5,1,2)

1

In [ ]:
x="You are the best"
print(x[::3])
print(x[::-1])
print(x[::1])

Y ehbt
tseb eht era uoY
You are the best


In [ ]:
L=[1,2,3,4]
L2=L
print(L)
print(L2)
L2[3]="four"
print(L)
print(L2)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 'four']
[1, 2, 3, 'four']


In [8]:
import numpy as np
a=np.array((1,2,3,4,5))
b=np.array((1,2,3,4,5),dtype="f")
c=np.array([ [ [-1,-2],[1,2],[3,4] ],[ [5,6],[7,8],[9,10] ]])
print(a.dtype)
print(a.dtype)
print(b.dtype)
print(c.ndim)
print(c[0][1])
print(c[1,0])
print(c)
print(c.shape)
c=c.reshape(2,2,3)
print(c)
print(c.shape)

int64
int64
float32
3
[1 2]
[5 6]
[[[-1 -2]
  [ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]]
(2, 3, 2)
[[[-1 -2  1]
  [ 2  3  4]]

 [[ 5  6  7]
  [ 8  9 10]]]
(2, 2, 3)


In [9]:
import numpy as np
x=np.array([0,2,1],ndmin=4)
A=np.arange(30,100,3)
B=np.random.permutation(np.arange(10))
print(x)
print(x.shape)
print(A)
print(B)
print(np.random.randint(20,30))
print(np.random.rand(10))

[[[[0 2 1]]]]
(1, 1, 1, 3)
[30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99]
[1 2 9 7 5 6 4 3 8 0]
23
[0.04113817 0.48624428 0.65920907 0.58000479 0.61378248 0.52763703
 0.3415723  0.13498225 0.91576484 0.05873574]
